name: Build on PR

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Generate prisma client
        run: npm run db:generate

      - name: Eslint check
        run: npm run lint
        
      - name: Run Build
        run: npm run build